/**
 * Service directory for the SERVICES page (CHANGE 007-D).
 *
 * Categories and service names reflect the maintenance and repair services
 * available through the network. Individual service names are drawn from the
 * existing DSN service catalog; no promotional copy is added here.
 */

export interface ServiceCategoryGroup {
  id: string;
  name: string;
  icon: string;
  description: string;
  services: string[];
}

export const SERVICE_DIRECTORY: ServiceCategoryGroup[] = [
  {
    id: "maintenance",
    name: "Maintenance",
    icon: "gauge",
    description:
      "Oil changes, scheduled maintenance, filters, fluids and preventive maintenance.",
    services: [
      "Oil & Filter Change — Conventional",
      "Oil & Filter Change — Synthetic Blend",
      "Oil & Filter Change — Full Synthetic",
      "Scheduled Maintenance Service",
      "Engine Air Filter Replacement",
      "Cabin Air Filter Replacement",
      "Coolant Flush & Replacement",
      "Brake Fluid Flush",
      "Power Steering Fluid Service",
      "Transmission Fluid Change",
      "Differential Fluid Service",
      "Transfer Case Fluid Replacement",
      "Spark Plug Replacement",
      "Serpentine Belt Replacement",
      "Timing Belt Replacement",
      "Battery Terminal End Servicing",
      "Wiper Blade Replacement",
      "Multi-Point Inspection",
      "Tire Rotation",
      "Parking Brake System Adjustment",
    ],
  },
  {
    id: "mechanical",
    name: "Mechanical Repairs",
    icon: "wrench",
    description:
      "Engine, drivetrain, electrical, cooling, braking and other mechanical repairs.",
    services: [
      "Engine Diagnosis",
      "Check Engine Light Diagnosis",
      "Water Pump Replacement",
      "Radiator Replacement",
      "Thermostat Replacement",
      "Head Gasket Replacement",
      "Timing Cover Gasket Replacement",
      "Valve Cover Gasket Replacement",
      "Fuel Pump Replacement",
      "High Pressure Fuel Pump Replacement",
      "Fuel Injector Service",
      "Alternator Replacement",
      "Starter Motor Replacement",
      "Battery Replacement",
      "Battery Cable Replacement",
      "Ignition Coil Replacement",
      "Oxygen Sensor Replacement",
      "Catalytic Converter Replacement",
      "Muffler Replacement",
      "Exhaust Pipe Replacement",
      "Transmission Repair",
      "Clutch Replacement",
      "Clutch Slave Cylinder Replacement",
      "CV Axle Replacement",
      "Driveshaft Support Bearing Replacement",
      "Differential Repair",
      "All Wheel Drive Diagnosis",
      "Brake Pad Replacement — Front",
      "Brake Pad Replacement — Rear",
      "Brake Pad & Rotor Replacement",
      "Brake Rotor Replacement",
      "Brake Caliper Replacement",
      "Brake Master Cylinder Replacement",
      "Brake Drum Replacement",
      "ABS Control Module Replacement",
      "ABS / Traction Control Diagnosis",
      "Shock & Strut Replacement",
      "Ball Joint Replacement",
      "Control Arm Replacement",
      "Tie Rod Replacement",
      "Steering Rack Replacement",
      "Sway Bar Link Replacement",
      "Wheel Bearing Replacement",
      "Wheel Alignment",
      "A/C Evacuation and Recharge",
      "A/C Compressor Replacement",
      "A/C Condenser Replacement",
      "A/C Expansion Valve Replacement",
      "Heater Core Replacement",
      "Blower Motor Replacement",
      "Electrical System Diagnosis",
      "Power Window Motor Replacement",
      "Fluid / Leak Diagnosis",
    ],
  },
  {
    id: "tires",
    name: "Tires",
    icon: "circle",
    description:
      "Replacement, repair, rotation, balancing and related tire services.",
    services: [
      "Tire Installation — 1 Tire",
      "Tire Installation — 2 Tires",
      "Tire Installation — 4 Tires",
      "Mount and Balance",
      "4 Wheel Balancing",
      "Tire Rotation & Balance",
      "Flat Tire Repair",
      "Tire Leak Repair / Patch",
      "Tire Pressure Monitoring Sensor Replacement",
      "Tire Pressure Monitoring System Reset",
      "Tire Pressure Warning Light Diagnosis",
      "Wheel Replacement",
      "Seasonal Tire Changeover",
      "Wheel Alignment",
    ],
  },
  {
    id: "glass",
    name: "Glass",
    icon: "glass",
    description: "Windshield and automotive glass repair and replacement.",
    services: [
      "Windshield Replacement",
      "Windshield Chip Repair",
      "Windshield Crack Repair",
      "Door Glass Replacement",
      "Rear Window Replacement",
      "Quarter Glass Replacement",
      "Power Window Regulator Replacement",
      "Windshield Wiper System Repair",
      "ADAS Windshield Camera Recalibration",
    ],
  },
  {
    id: "collision",
    name: "Collision",
    icon: "collision",
    description: "Body repair, paint and collision services.",
    services: [
      "Collision Damage Estimate",
      "Body Panel Repair",
      "Body Panel Replacement",
      "Bumper Repair",
      "Bumper Replacement",
      "Fender Repair / Replacement",
      "Dent Removal",
      "Paint Refinishing",
      "Paint Touch-Up",
      "Frame & Structural Repair",
      "Headlamp / Tail Lamp Replacement",
      "Mirror Replacement",
    ],
  },
  {
    id: "roadside",
    name: "Roadside Assistance",
    icon: "roadside",
    description: "Help when a vehicle cannot continue operating normally.",
    services: [
      "Towing",
      "Jump Start",
      "Battery Delivery & Installation",
      "Flat Tire Change",
      "Fuel Delivery",
      "Lockout Service",
      "Winch / Extrication Service",
      "Mobile Diagnostic Assistance",
    ],
  },
  {
    id: "inspections",
    name: "Inspections",
    icon: "clipboard",
    description: "Vehicle inspections and related inspection services.",
    services: [
      "State Safety Inspection",
      "State Emissions Inspection",
      "Smog Check",
      "Inspection Sticker",
      "Pre-Purchase Inspection",
      "Pre-Registration Inspection",
      "Commercial Vehicle Inspection",
      "Multi-Point Vehicle Inspection",
      "Brake System Inspection / Diagnosis",
      "Suspension & Steering Inspection",
    ],
  },
];
